# Rendered by the postgres-config Argo CD Application.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

resources:
  - manifests/cluster.yaml
  - manifests/databases.yaml
  - manifests/podmonitor.yaml
